version: '3'
services:
  admin:
    build:
      dockerfile: apps/admin/Dockerfile
      context: ./
    ports:
      - "8040:4000"

  api-document-generator:
    build:
      dockerfile: apps/api/document-generator/Dockerfile
      context: ./
    ports:
      - "8030:3333"
